export const SEED_ROUTES = [
  // ── Bankura city routes ──
  {
    cityId: 'bankura',
    from: 'Indas',
    to: 'Kolkata',
    fromHi: 'इंदास',
    toHi: 'कोलकाता',
    distance: '120 km',
    estimatedTime: '3 hours',
    suggestedFareMin: 250,
    suggestedFareMax: 400,
  },
  {
    cityId: 'bankura',
    from: 'Bankura',
    to: 'Kolkata',
    fromHi: 'बाँकुड़ा',
    toHi: 'कोलकाता',
    distance: '230 km',
    estimatedTime: '5 hours',
    suggestedFareMin: 400,
    suggestedFareMax: 600,
  },
  {
    cityId: 'bankura',
    from: 'Bishnupur',
    to: 'Kolkata',
    fromHi: 'बिष्णुपुर',
    toHi: 'कोलकाता',
    distance: '200 km',
    estimatedTime: '4.5 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  {
    cityId: 'bankura',
    from: 'Durgapur',
    to: 'Kolkata',
    fromHi: 'दुर्गापुर',
    toHi: 'कोलकाता',
    distance: '180 km',
    estimatedTime: '3.5 hours',
    suggestedFareMin: 300,
    suggestedFareMax: 500,
  },
  {
    cityId: 'bankura',
    from: 'Indas',
    to: 'Bankura',
    fromHi: 'इंदास',
    toHi: 'बाँकुड़ा',
    distance: '45 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 100,
    suggestedFareMax: 200,
  },
  {
    cityId: 'bankura',
    from: 'Bankura',
    to: 'Durgapur',
    fromHi: 'बाँकुड़ा',
    toHi: 'दुर्गापुर',
    distance: '80 km',
    estimatedTime: '2 hours',
    suggestedFareMin: 150,
    suggestedFareMax: 250,
  },
  {
    cityId: 'bankura',
    from: 'Indas',
    to: 'Burdwan',
    fromHi: 'इंदास',
    toHi: 'बर्दवान',
    distance: '90 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 150,
    suggestedFareMax: 280,
  },
  {
    cityId: 'bankura',
    from: 'Burdwan',
    to: 'Kolkata',
    fromHi: 'बर्दवान',
    toHi: 'कोलकाता',
    distance: '100 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 200,
    suggestedFareMax: 350,
  },
  {
    cityId: 'bankura',
    from: 'Asansol',
    to: 'Kolkata',
    fromHi: 'आसनसोल',
    toHi: 'कोलकाता',
    distance: '200 km',
    estimatedTime: '4 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  {
    cityId: 'bankura',
    from: 'Asansol',
    to: 'Durgapur',
    fromHi: 'आसनसोल',
    toHi: 'दुर्गापुर',
    distance: '40 km',
    estimatedTime: '1 hour',
    suggestedFareMin: 80,
    suggestedFareMax: 150,
  },
  {
    cityId: 'bankura',
    from: 'Kotulpur',
    to: 'Bankura',
    fromHi: 'कोतुलपुर',
    toHi: 'बाँकुड़ा',
    distance: '35 km',
    estimatedTime: '1 hour',
    suggestedFareMin: 80,
    suggestedFareMax: 150,
  },
  {
    cityId: 'bankura',
    from: 'Kotulpur',
    to: 'Bishnupur',
    fromHi: 'कोतुलपुर',
    toHi: 'बिष्णुपुर',
    distance: '25 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 60,
    suggestedFareMax: 120,
  },
  // ── Kolkata city routes ──
  {
    cityId: 'kolkata',
    from: 'Kolkata',
    to: 'Arambagh',
    fromHi: 'कोलकाता',
    toHi: 'आरामबाग',
    distance: '100 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 200,
    suggestedFareMax: 350,
  },
  {
    cityId: 'kolkata',
    from: 'Kolkata',
    to: 'Karunamoyee',
    fromHi: 'कोलकाता',
    toHi: 'करुणामयी',
    distance: '15 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 50,
    suggestedFareMax: 100,
  },
  {
    cityId: 'kolkata',
    from: 'Kolkata',
    to: 'Durgapur',
    fromHi: 'कोलकाता',
    toHi: 'दुर्गापुर',
    distance: '180 km',
    estimatedTime: '3.5 hours',
    suggestedFareMin: 300,
    suggestedFareMax: 500,
  },
  {
    cityId: 'kolkata',
    from: 'Kolkata',
    to: 'Asansol',
    fromHi: 'कोलकाता',
    toHi: 'आसनसोल',
    distance: '200 km',
    estimatedTime: '4 hours',
    suggestedFareMin: 350,
    suggestedFareMax: 550,
  },
  // ── Raipur city routes ──
  {
    cityId: 'raipur',
    from: 'Raipur',
    to: 'Bilaspur',
    fromHi: 'रायपुर',
    toHi: 'बिलासपुर',
    distance: '130 km',
    estimatedTime: '2.5 hours',
    suggestedFareMin: 200,
    suggestedFareMax: 350,
  },
  {
    cityId: 'raipur',
    from: 'Raipur',
    to: 'Durg',
    fromHi: 'रायपुर',
    toHi: 'दुर्ग',
    distance: '30 km',
    estimatedTime: '45 mins',
    suggestedFareMin: 80,
    suggestedFareMax: 150,
  },
  {
    cityId: 'raipur',
    from: 'Raipur',
    to: 'Rajnandgaon',
    fromHi: 'रायपुर',
    toHi: 'राजनांदगाँव',
    distance: '70 km',
    estimatedTime: '1.5 hours',
    suggestedFareMin: 120,
    suggestedFareMax: 200,
  },
  {
    cityId: 'raipur',
    from: 'Raipur',
    to: 'Jagdalpur',
    fromHi: 'रायपुर',
    toHi: 'जगदलपुर',
    distance: '300 km',
    estimatedTime: '6 hours',
    suggestedFareMin: 500,
    suggestedFareMax: 800,
  },
];
